CREATE TABLE `aud_vendedores` (
`Id` BIGINT NOT NULL AUTO_INCREMENT,
`FechaAud` DATETIME NOT NULL,
`UsuarioAud` VARCHAR(30) NOT NULL,
`IP` VARCHAR(40) NOT NULL,
`UserAgent` VARCHAR(255) NULL,
`Aplicacion` VARCHAR(50) NOT NULL,
`TipoAud` CHAR(1) NOT NULL,
  `IdUsuario` int unsigned NOT NULL,
  `Apellidos` varchar(60) NOT NULL,
  `Nombres` varchar(60) NOT NULL,
  `CUIL` varchar(11) NOT NULL,
  `DNI` varchar(10) NOT NULL,
  `Email` varchar(100) NOT NULL,
  `Telefono` varchar(15) NOT NULL,
  `Domicilio` varchar(100) NOT NULL,
  `Cuenta` varchar(20) NOT NULL,
  `Contrasenia` char(60) NOT NULL,
PRIMARY KEY (`Id`),
INDEX `IX_FechaAud` (`FechaAud` ASC),
INDEX `IX_Usuario` (`UsuarioAud` ASC),
INDEX `IX_IP` (`IP` ASC),
INDEX `IX_Aplicacion` (`Aplicacion` ASC)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
